/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MyLayoutImport } from './routes/my/_layout'
import { Route as MyLayoutIndexImport } from './routes/my/_layout.index'
import { Route as MyWishlistCreateImport } from './routes/my/wishlist.create'
import { Route as MyLayoutMessageImport } from './routes/my/_layout.message'
import { Route as MyWishlistWishlistIdItemsImport } from './routes/my/wishlist.$wishlistId.items'
import { Route as MyLayoutWishlistWishlistIdIndexImport } from './routes/my/_layout.wishlist.$wishlistId.index'
import { Route as MyWishlistWishlistIdItemsWishitemIdImport } from './routes/my/wishlist.$wishlistId.items.$wishitemId'

// Create Virtual Routes

const MyImport = createFileRoute('/my')()

// Create/Update Routes

const MyRoute = MyImport.update({
  path: '/my',
  getParentRoute: () => rootRoute,
} as any)

const MyLayoutRoute = MyLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => MyRoute,
} as any)

const MyLayoutIndexRoute = MyLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => MyLayoutRoute,
} as any)

const MyWishlistCreateRoute = MyWishlistCreateImport.update({
  path: '/wishlist/create',
  getParentRoute: () => MyRoute,
} as any)

const MyLayoutMessageRoute = MyLayoutMessageImport.update({
  path: '/message',
  getParentRoute: () => MyLayoutRoute,
} as any)

const MyWishlistWishlistIdItemsRoute = MyWishlistWishlistIdItemsImport.update({
  path: '/wishlist/$wishlistId/items',
  getParentRoute: () => MyRoute,
} as any)

const MyLayoutWishlistWishlistIdIndexRoute =
  MyLayoutWishlistWishlistIdIndexImport.update({
    path: '/wishlist/$wishlistId/',
    getParentRoute: () => MyLayoutRoute,
  } as any)

const MyWishlistWishlistIdItemsWishitemIdRoute =
  MyWishlistWishlistIdItemsWishitemIdImport.update({
    path: '/$wishitemId',
    getParentRoute: () => MyWishlistWishlistIdItemsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyImport
      parentRoute: typeof rootRoute
    }
    '/my/_layout': {
      id: '/my/_layout'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyLayoutImport
      parentRoute: typeof MyRoute
    }
    '/my/_layout/message': {
      id: '/my/_layout/message'
      path: '/message'
      fullPath: '/my/message'
      preLoaderRoute: typeof MyLayoutMessageImport
      parentRoute: typeof MyLayoutImport
    }
    '/my/wishlist/create': {
      id: '/my/wishlist/create'
      path: '/wishlist/create'
      fullPath: '/my/wishlist/create'
      preLoaderRoute: typeof MyWishlistCreateImport
      parentRoute: typeof MyImport
    }
    '/my/_layout/': {
      id: '/my/_layout/'
      path: '/'
      fullPath: '/my/'
      preLoaderRoute: typeof MyLayoutIndexImport
      parentRoute: typeof MyLayoutImport
    }
    '/my/wishlist/$wishlistId/items': {
      id: '/my/wishlist/$wishlistId/items'
      path: '/wishlist/$wishlistId/items'
      fullPath: '/my/wishlist/$wishlistId/items'
      preLoaderRoute: typeof MyWishlistWishlistIdItemsImport
      parentRoute: typeof MyImport
    }
    '/my/wishlist/$wishlistId/items/$wishitemId': {
      id: '/my/wishlist/$wishlistId/items/$wishitemId'
      path: '/$wishitemId'
      fullPath: '/my/wishlist/$wishlistId/items/$wishitemId'
      preLoaderRoute: typeof MyWishlistWishlistIdItemsWishitemIdImport
      parentRoute: typeof MyWishlistWishlistIdItemsImport
    }
    '/my/_layout/wishlist/$wishlistId/': {
      id: '/my/_layout/wishlist/$wishlistId/'
      path: '/wishlist/$wishlistId'
      fullPath: '/my/wishlist/$wishlistId'
      preLoaderRoute: typeof MyLayoutWishlistWishlistIdIndexImport
      parentRoute: typeof MyLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  MyRoute: MyRoute.addChildren({
    MyLayoutRoute: MyLayoutRoute.addChildren({
      MyLayoutMessageRoute,
      MyLayoutIndexRoute,
      MyLayoutWishlistWishlistIdIndexRoute,
    }),
    MyWishlistCreateRoute,
    MyWishlistWishlistIdItemsRoute: MyWishlistWishlistIdItemsRoute.addChildren({
      MyWishlistWishlistIdItemsWishitemIdRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/my"
      ]
    },
    "/my": {
      "filePath": "my",
      "children": [
        "/my/_layout",
        "/my/wishlist/create",
        "/my/wishlist/$wishlistId/items"
      ]
    },
    "/my/_layout": {
      "filePath": "my/_layout.tsx",
      "parent": "/my",
      "children": [
        "/my/_layout/message",
        "/my/_layout/",
        "/my/_layout/wishlist/$wishlistId/"
      ]
    },
    "/my/_layout/message": {
      "filePath": "my/_layout.message.tsx",
      "parent": "/my/_layout"
    },
    "/my/wishlist/create": {
      "filePath": "my/wishlist.create.tsx",
      "parent": "/my"
    },
    "/my/_layout/": {
      "filePath": "my/_layout.index.tsx",
      "parent": "/my/_layout"
    },
    "/my/wishlist/$wishlistId/items": {
      "filePath": "my/wishlist.$wishlistId.items.tsx",
      "parent": "/my",
      "children": [
        "/my/wishlist/$wishlistId/items/$wishitemId"
      ]
    },
    "/my/wishlist/$wishlistId/items/$wishitemId": {
      "filePath": "my/wishlist.$wishlistId.items.$wishitemId.tsx",
      "parent": "/my/wishlist/$wishlistId/items"
    },
    "/my/_layout/wishlist/$wishlistId/": {
      "filePath": "my/_layout.wishlist.$wishlistId.index.tsx",
      "parent": "/my/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
