/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MyWishlistCreateImport } from './routes/my/wishlist.create'
import { Route as MyWishlistWishlistIdIndexImport } from './routes/my/wishlist.$wishlistId.index'
import { Route as MyWishlistWishlistIdItemsImport } from './routes/my/wishlist.$wishlistId.items'
import { Route as MyWishlistWishlistIdItemsWishitemIdImport } from './routes/my/wishlist.$wishlistId.items.$wishitemId'

// Create/Update Routes

const MyWishlistCreateRoute = MyWishlistCreateImport.update({
  path: '/my/wishlist/create',
  getParentRoute: () => rootRoute,
} as any)

const MyWishlistWishlistIdIndexRoute = MyWishlistWishlistIdIndexImport.update({
  path: '/my/wishlist/$wishlistId/',
  getParentRoute: () => rootRoute,
} as any)

const MyWishlistWishlistIdItemsRoute = MyWishlistWishlistIdItemsImport.update({
  path: '/my/wishlist/$wishlistId/items',
  getParentRoute: () => rootRoute,
} as any)

const MyWishlistWishlistIdItemsWishitemIdRoute =
  MyWishlistWishlistIdItemsWishitemIdImport.update({
    path: '/$wishitemId',
    getParentRoute: () => MyWishlistWishlistIdItemsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my/wishlist/create': {
      preLoaderRoute: typeof MyWishlistCreateImport
      parentRoute: typeof rootRoute
    }
    '/my/wishlist/$wishlistId/items': {
      preLoaderRoute: typeof MyWishlistWishlistIdItemsImport
      parentRoute: typeof rootRoute
    }
    '/my/wishlist/$wishlistId/': {
      preLoaderRoute: typeof MyWishlistWishlistIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/my/wishlist/$wishlistId/items/$wishitemId': {
      preLoaderRoute: typeof MyWishlistWishlistIdItemsWishitemIdImport
      parentRoute: typeof MyWishlistWishlistIdItemsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  MyWishlistCreateRoute,
  MyWishlistWishlistIdItemsRoute.addChildren([
    MyWishlistWishlistIdItemsWishitemIdRoute,
  ]),
  MyWishlistWishlistIdIndexRoute,
])

/* prettier-ignore-end */
