/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MyWishlistCreateImport } from './routes/my/wishlist.create'
import { Route as MyWishlistWishlistIdIndexImport } from './routes/my/wishlist.$wishlistId.index'
import { Route as MyWishlistWishlistIdItemsImport } from './routes/my/wishlist.$wishlistId.items'
import { Route as MyWishlistWishlistIdItemsWishitemIdImport } from './routes/my/wishlist.$wishlistId.items.$wishitemId'

// Create/Update Routes

const MyWishlistCreateRoute = MyWishlistCreateImport.update({
  path: '/my/wishlist/create',
  getParentRoute: () => rootRoute,
} as any)

const MyWishlistWishlistIdIndexRoute = MyWishlistWishlistIdIndexImport.update({
  path: '/my/wishlist/$wishlistId/',
  getParentRoute: () => rootRoute,
} as any)

const MyWishlistWishlistIdItemsRoute = MyWishlistWishlistIdItemsImport.update({
  path: '/my/wishlist/$wishlistId/items',
  getParentRoute: () => rootRoute,
} as any)

const MyWishlistWishlistIdItemsWishitemIdRoute =
  MyWishlistWishlistIdItemsWishitemIdImport.update({
    path: '/$wishitemId',
    getParentRoute: () => MyWishlistWishlistIdItemsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my/wishlist/create': {
      id: '/my/wishlist/create'
      path: '/my/wishlist/create'
      fullPath: '/my/wishlist/create'
      preLoaderRoute: typeof MyWishlistCreateImport
      parentRoute: typeof rootRoute
    }
    '/my/wishlist/$wishlistId/items': {
      id: '/my/wishlist/$wishlistId/items'
      path: '/my/wishlist/$wishlistId/items'
      fullPath: '/my/wishlist/$wishlistId/items'
      preLoaderRoute: typeof MyWishlistWishlistIdItemsImport
      parentRoute: typeof rootRoute
    }
    '/my/wishlist/$wishlistId/': {
      id: '/my/wishlist/$wishlistId/'
      path: '/my/wishlist/$wishlistId'
      fullPath: '/my/wishlist/$wishlistId'
      preLoaderRoute: typeof MyWishlistWishlistIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/my/wishlist/$wishlistId/items/$wishitemId': {
      id: '/my/wishlist/$wishlistId/items/$wishitemId'
      path: '/$wishitemId'
      fullPath: '/my/wishlist/$wishlistId/items/$wishitemId'
      preLoaderRoute: typeof MyWishlistWishlistIdItemsWishitemIdImport
      parentRoute: typeof MyWishlistWishlistIdItemsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  MyWishlistCreateRoute,
  MyWishlistWishlistIdItemsRoute: MyWishlistWishlistIdItemsRoute.addChildren({
    MyWishlistWishlistIdItemsWishitemIdRoute,
  }),
  MyWishlistWishlistIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/my/wishlist/create",
        "/my/wishlist/$wishlistId/items",
        "/my/wishlist/$wishlistId/"
      ]
    },
    "/my/wishlist/create": {
      "filePath": "my/wishlist.create.tsx"
    },
    "/my/wishlist/$wishlistId/items": {
      "filePath": "my/wishlist.$wishlistId.items.tsx",
      "children": [
        "/my/wishlist/$wishlistId/items/$wishitemId"
      ]
    },
    "/my/wishlist/$wishlistId/": {
      "filePath": "my/wishlist.$wishlistId.index.tsx"
    },
    "/my/wishlist/$wishlistId/items/$wishitemId": {
      "filePath": "my/wishlist.$wishlistId.items.$wishitemId.tsx",
      "parent": "/my/wishlist/$wishlistId/items"
    }
  }
}
ROUTE_MANIFEST_END */
